### ISSUE TITLE
[master] SqlServerParser排序列自动拼接到SQL查询列中的问题

### ISSUE THREAD

**Issue by RavenCM** [open-hand/choerodon-starters#7]
```java
// io/choerodon/mybatis/pagehelper/parser/SqlServerParser.java:449
selectMap.put(expItem.getExpression().toString(), expItem);
```
上句代码将查询字段中的别名也作为KEY存到了Map中。
```
// io/choerodon/mybatis/pagehelper/parser/SqlServerParser.java:469
SelectExpressionItem selectExpressionItem = selectMap.get(expression.toString());
```
上句代码判断排序列是否存在于查询列中时去获取KEY是否存在，排序字段是可以不写表别名的，而且`@io.choerodon.mybatis.pagehelper.annotation.SortDefault`注解中指定的排序字段也不会添加表别名。
当多表关联，并且排序字段存在于多表中，又没有写表别名时，会抛出异常
```java
com.microsoft.sqlserver.jdbc.SQLServerException: Ambiguous column name 'xxx'.
```

**Comment by superlee9527** [comment]
你这种情况应该是doPageAndSort的使用中没有设置别名map，看下我提的issue，里面有一些用法

**Comment by superlee9527** [comment]
动态拼接的排序字段，某些表单一般是事先确定好的，也就是要和产品沟通表单具体那些列要排序，之后开发者就根据sql设置别名了，不一定每个字段都要放到map里面。

**Comment by RavenCM** [comment]
> 动态拼接的排序字段，某些表单一般是事先确定好的，也就是要和产品沟通表单具体那些列要排序，之后开发者就根据sql设置别名了，不一定每个字段都要放到map里面。

有一个问题就是这种方法把SQL别名硬编码到Java代码中，而且如果有新的排序字段，是需要修改代码的。个人还是觉得修改一下这个判断比较好，你们可以判断一下框架会不会做调整，不做调整的话我们准备覆盖。

**Comment by superlee9527** [comment]
嗯，是的，这种硬编码方式确实不好，开发这个功能的时候，对于这种join的关联查询，前端的排序字段和xml里面的数据库字段无法建立直接关系，牵扯到别名的问题就更不好处理了，所以就采取了一个map建立映射，在开发过程中让开发者决定这种映射关系，我最近也在考虑怎么处理这个问题，或者你那边有什么解决方案可以讨论下 :p

**Comment by RavenCM** [comment]
如果只是上边的这个问题的话：我打算如果列有别名就取别名作为Map的key，如果没有别名的话取真实的列名(**去掉表别名前缀**)作为key，如果别名已经存在则不存入map。
